version: '3'
services:
  credit-service-dev:
    container_name: credit-service
    build:
        context: .
        dockerfile: Dockerfile
    image: credit-service:latest
    ports:
      - "8100:8100"
    depends_on:
      - credit-db-dev
    networks:
      - credit-network-dev
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - CREDIT_DB_HOST=credit-db
      - CREDIT_DB_PORT=5432
      - CREDIT_DB_NAME=credit-db
      - CREDIT_DB_USERNAME=credit-db
      - CREDIT_DB_PASSWORD=db_@password
      - CONTAINER_PORT=8100

  credit-db-dev:
    image: 'postgres:15.3-alpine'
    container_name: credit-service-db
    ports:
      - ":5432"
    networks:
      - credit-network-dev
    environment:
      - POSTGRES_USER=credit-db
      - POSTGRES_PASSWORD=db_@password

networks:
  credit-network-dev: