spring:
  datasource:
    url: jdbc:postgresql://${CREDIT_SERVICE_HOST}:${CREDIT_SERVICE_PORT}}/{CREDIT_DB_NAME}}
    driverClassName: org.postgresql.Driver
    username: ${CREDIT_DB_USERNAME}
    password: ${CREDIT_DB_PASSWORD}

server:
  port: 8091